namespace SpriteKind {
    export const OBJETOS = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.OBJETOS, function (sprite, otherSprite) {
    sprites.destroy(otherSprite, effects.disintegrate, 100)
    PLAYER.startEffect(effects.confetti, 200)
    info.changeScoreBy(1)
    countPizzas += 1
    actualizarMarcadores()
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    PLAYER.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . f d 1 1 1 1 1 1 1 d f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 d f 1 1 f . . . . 
        . . . . . f d f . f d f . . . . 
        . . . . . f f . . f f f . . . . 
        `)
    animation.runImageAnimation(
    PLAYER,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f f . . . . . 
        . . . f d 1 1 1 1 1 d f . . . . 
        . . f d 1 1 1 1 1 1 1 d f . . . 
        . . f 1 1 1 1 1 1 1 1 1 f . . . 
        . . f 1 1 1 1 1 1 1 1 1 f . . . 
        . . f 1 1 1 1 1 1 1 1 1 f . . . 
        . . f 1 1 1 1 1 1 1 1 1 f . . . 
        . . . f d 1 1 1 1 1 d f . . . . 
        . . . . f 1 1 1 1 1 f . . . . . 
        . . . . f 1 1 1 1 d f . . . . . 
        . . . . f 1 1 d d d f . . . . . 
        . . . . f 1 d f f d f . . . . . 
        . . . . f d f . . f . . . . . . 
        . . . . f f . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . f d 1 1 1 1 1 1 1 d f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f d 1 1 1 1 f . . . . 
        . . . . . f d d d 1 1 f . . . . 
        . . . . . f d d f d 1 f . . . . 
        . . . . . . f f . f d f . . . . 
        . . . . . . . . . . f f . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    150,
    true
    )
})
function actualizarMarcadores () {
    txtPizzas.setText("Pizzas: " + countPizzas)
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    PLAYER.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . f d 1 1 1 1 1 f . . . 
        . . . . f d 1 1 1 1 1 1 1 f . . 
        . . . . f 1 f 1 1 1 1 1 1 f . . 
        . . . . f 1 f 1 1 1 1 1 1 f . . 
        . . . . f 1 1 1 1 1 1 1 1 f . . 
        . . . . f 1 1 1 1 1 1 1 d f . . 
        . . . . . f d 1 1 1 1 d f . . . 
        . . . . . . f 1 1 1 1 f . . . . 
        . . . . . . f 1 1 1 1 f . . . . 
        . . . . . . f 1 1 1 d f . . . . 
        . . . . . . f 1 d f d f . . . . 
        . . . . . . f d f f d f . . . . 
        . . . . . . f f . . f f . . . . 
        `)
    animation.runImageAnimation(
    PLAYER,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f d 1 1 1 1 1 f . . . . 
        . . . f d 1 1 1 1 1 1 1 f . . . 
        . . . f 1 f 1 1 1 1 1 1 f . . . 
        . . . f 1 f 1 1 1 1 1 1 f . . . 
        . . . f 1 1 1 1 1 1 1 1 f . . . 
        . . . f 1 1 1 1 1 1 1 d f . . . 
        . . . . f d 1 1 1 1 d f . . . . 
        . . . . . f 1 1 1 1 f . . . . . 
        . . . . . f 1 1 1 d f . . . . . 
        . . . . . f 1 1 d d f . . . . . 
        . . . . . f d d f d f . . . . . 
        . . . . . f d f f f . . . . . . 
        . . . . . f f . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f d 1 1 1 1 1 f . . . . 
        . . . f d 1 1 1 1 1 1 1 f . . . 
        . . . f 1 f 1 1 1 1 1 1 f . . . 
        . . . f 1 f 1 1 1 1 1 1 f . . . 
        . . . f 1 1 1 1 1 1 1 1 f . . . 
        . . . f 1 1 1 1 1 1 1 d f . . . 
        . . . . f d 1 1 1 1 d f . . . . 
        . . . . . f 1 1 1 1 f . . . . . 
        . . . . . f 1 1 1 d f . . . . . 
        . . . . . f d d d d f . . . . . 
        . . . . . . f d f d f . . . . . 
        . . . . . . . f f d f . . . . . 
        . . . . . . . . . f f . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    150,
    true
    )
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    PLAYER.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 1 1 1 1 1 d f . . . . . 
        . . f 1 1 1 1 1 1 1 d f . . . . 
        . . f 1 1 1 1 1 1 f 1 f . . . . 
        . . f 1 1 1 1 1 1 f 1 f . . . . 
        . . f 1 1 1 1 1 1 1 1 f . . . . 
        . . f 1 1 1 1 1 1 1 1 f . . . . 
        . . . f d 1 1 1 1 d f . . . . . 
        . . . . f 1 1 1 1 f . . . . . . 
        . . . . f 1 1 1 1 f . . . . . . 
        . . . . f d 1 1 1 f . . . . . . 
        . . . . f d f d 1 f . . . . . . 
        . . . . f d f f d f . . . . . . 
        . . . . f f . . f f . . . . . . 
        `)
    animation.runImageAnimation(
    PLAYER,
    [img`
        . . . . . f f f f f f . . . . . 
        . . . . f 1 1 1 1 1 d f . . . . 
        . . . f 1 1 1 1 1 1 1 d f . . . 
        . . . f 1 1 1 1 1 1 f 1 f . . . 
        . . . f 1 1 1 1 1 1 f 1 f . . . 
        . . . f 1 1 1 1 1 1 1 1 f . . . 
        . . . f d 1 1 1 1 1 1 1 f . . . 
        . . . . f d 1 1 1 1 d f . . . . 
        . . . . . f 1 1 1 1 f . . . . . 
        . . . . . f d 1 1 1 f . . . . . 
        . . . . . f d d 1 1 f . . . . . 
        . . . . . f d f d d f . . . . . 
        . . . . . . f f f d f . . . . . 
        . . . . . . . . . f f . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f 1 1 1 1 1 d f . . . . 
        . . . f 1 1 1 1 1 1 1 d f . . . 
        . . . f 1 1 1 1 1 1 f 1 f . . . 
        . . . f 1 1 1 1 1 1 f 1 f . . . 
        . . . f 1 1 1 1 1 1 1 1 f . . . 
        . . . f d 1 1 1 1 1 1 1 f . . . 
        . . . . f d 1 1 1 1 d f . . . . 
        . . . . . f 1 1 1 1 f . . . . . 
        . . . . . f d 1 1 1 f . . . . . 
        . . . . . f d d d d f . . . . . 
        . . . . . f d f d f . . . . . . 
        . . . . . f d f f . . . . . . . 
        . . . . . f f . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    150,
    true
    )
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    PLAYER.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . f d 1 1 1 1 1 1 1 d f . . 
        . . . f 1 1 f 1 1 1 f 1 1 f . . 
        . . . f 1 1 f 1 1 1 f 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 d f 1 1 f . . . . 
        . . . . . f d f . f d f . . . . 
        . . . . . f f . . f f f . . . . 
        `)
    animation.runImageAnimation(
    PLAYER,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . f d 1 1 1 1 1 1 1 d f . . 
        . . . f 1 1 f 1 1 1 f 1 1 f . . 
        . . . f 1 1 f 1 1 1 f 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . f 1 1 1 1 1 1 1 1 1 f . . 
        . . . . f d 1 1 1 1 1 d f . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 1 1 1 1 f . . . . 
        . . . . . f 1 f f 1 1 f . . . . 
        . . . . . . f . . f d f . . . . 
        . . . . . . . . . f f f . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f f . . . . . 
        . . . f d 1 1 1 1 1 d f . . . . 
        . . f d 1 1 1 1 1 1 1 d f . . . 
        . . f 1 1 f 1 1 1 f 1 1 f . . . 
        . . f 1 1 f 1 1 1 f 1 1 f . . . 
        . . f 1 1 1 1 1 1 1 1 1 f . . . 
        . . f 1 1 1 1 1 1 1 1 1 f . . . 
        . . . f d 1 1 1 1 1 d f . . . . 
        . . . . f 1 1 1 1 1 f . . . . . 
        . . . . f 1 1 1 1 1 f . . . . . 
        . . . . f 1 1 1 1 1 f . . . . . 
        . . . . f 1 d f 1 1 f . . . . . 
        . . . . f d f . f f . . . . . . 
        . . . . f f . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    150,
    true
    )
})
function Crear_Basura () {
    BASURA = sprites.create(img`
        ........................
        ...........fffff........
        ..........feeeeeff......
        .........feeeeeeeeff....
        ........feeeeeeeeefeff..
        .......f9eeeeeeeeefeeef.
        .......f99eeeeeeeefee4f.
        .......fbbbbeeeeeeef44f.
        .....fffbbbbbbeeeeefff..
        ....f6bbfbbbbbbffff.....
        ....f66bfbbbbbfbbbbf....
        ....f666fbbbbfbbbb6f....
        .....fff.ffffbbbbb66f...
        .............fb66666f...
        .............f666666f...
        ..............ffffff....
        ........................
        `, SpriteKind.OBJETOS)
    PIZZA = sprites.create(img`
        ....................
        ....................
        ..........ffff......
        ........ffeaaf......
        .......feeefff......
        ......feeff557f.....
        .....feef555fff.....
        ....feef555f22f.....
        ...feef5555f22f.....
        ...fef5ff555ff5f....
        ..feeff22f55555f....
        ..faf5f27f55557f....
        ..fea55ff555557f....
        ..fff5555555ff57f...
        .....fffff5f27f7f...
        .........ffff277f...
        .............ffff...
        ....................
        ....................
        ....................
        `, SpriteKind.OBJETOS)
    BASURA.setPosition(randint(0, 260), randint(0, 260))
    PIZZA.setPosition(randint(0, 260), randint(0, 260))
    animation.runImageAnimation(
    BASURA,
    [img`
        .......................
        .......................
        ......f................
        .....f.................
        .........fffff.........
        ........feeeeeff.......
        .......feeeeeeeeff.....
        ......feeeeeeeeefeff...
        .....f9eeeeeeeeefeeef..
        .....f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        ...fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff......
        ..f66bfbbbbbfbbbbf.....
        ..f666fbbbbfbbbb6f.....
        ...fff.ffffbbbbb66f....
        ...........fb66666f....
        ...........f666666f....
        ............ffffff.....
        .....................f.
        ....................f..
        .......................
        .......................
        `,img`
        .......................
        ...........f...........
        .............f.........
        .......................
        .........fffff.........
        ........feeeeeff.......
        .......feeeeeeeeff.....
        ......feeeeeeeeefeff...
        .....f9eeeeeeeeefeeef..
        .....f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        ...fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff......
        ..f66bfbbbbbfbbbbf.....
        ..f666fbbbbfbbbb6f.....
        ...fff.ffffbbbbb66f....
        ...........fb66666f....
        ...........f666666f....
        ............ffffff.....
        .......................
        .......................
        ................f.f....
        .......................
        `,img`
        .......................
        .......................
        .......................
        .................f.....
        .........fffff....f....
        ........feeeeeff.......
        .......feeeeeeeeff.....
        ......feeeeeeeeefeff...
        .....f9eeeeeeeeefeeef..
        .....f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        ...fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff......
        ..f66bfbbbbbfbbbbf.....
        ..f666fbbbbfbbbb6f.....
        ...fff.ffffbbbbb66f....
        ...........fb66666f....
        ...........f666666f....
        ............ffffff.....
        .......................
        .......................
        ............ff.........
        .......................
        `,img`
        .......................
        .......................
        .......................
        .......................
        .........fffff.........
        ........feeeeeff.....f.
        .......feeeeeeeeff.....
        ......feeeeeeeeefeff..f
        .....f9eeeeeeeeefeeef..
        .....f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        ...fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff......
        ..f66bfbbbbbfbbbbf.....
        ..f666fbbbbfbbbb6f.....
        ...fff.ffffbbbbb66f....
        ...........fb66666f....
        ...........f666666f....
        ............ffffff.....
        .......f...............
        .........f.............
        .......................
        .......................
        `,img`
        .......................
        .......................
        .......................
        .......................
        .........fffff.........
        ........feeeeeff.......
        .......feeeeeeeeff.....
        ......feeeeeeeeefeff...
        .....f9eeeeeeeeefeeef..
        .....f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        ...fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff....f.
        ..f66bfbbbbbfbbbbf.....
        ..f666fbbbbfbbbb6f...f.
        ...fff.ffffbbbbb66f....
        ...........fb66666f....
        ..f........f666666f....
        ....f.......ffffff.....
        .......................
        .......................
        .......................
        .......................
        `,img`
        .......................
        .......................
        .......................
        .......................
        .........fffff.........
        ........feeeeeff.......
        .......feeeeeeeeff.....
        ......feeeeeeeeefeff...
        .....f9eeeeeeeeefeeef..
        .....f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        ...fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff......
        ..f66bfbbbbbfbbbbf.....
        f.f666fbbbbfbbbb6f.....
        ...fff.ffffbbbbb66f....
        .f.........fb66666f....
        ...........f666666f....
        ............ffffff..f..
        .......................
        ...................f...
        .......................
        .......................
        `,img`
        .......................
        .......................
        .......................
        .......................
        .........fffff.........
        ........feeeeeff.......
        .......feeeeeeeeff.....
        ......feeeeeeeeefeff...
        .....f9eeeeeeeeefeeef..
        ..f..f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        .f.fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff......
        ..f66bfbbbbbfbbbbf.....
        ..f666fbbbbfbbbb6f.....
        ...fff.ffffbbbbb66f....
        ...........fb66666f....
        ...........f666666f....
        ............ffffff.....
        .......................
        .......................
        .............f.f.......
        .......................
        `,img`
        .......................
        .......................
        .......................
        .......................
        .....f...fffff.........
        ........feeeeeff.......
        ...f...feeeeeeeeff.....
        ......feeeeeeeeefeff...
        ....ff9eeeeeeeeefeeef..
        .....f99eeeeeeeefee4f..
        .....fbbbbeeeeeeef44f..
        ...fffbbbbbbeeeeefff...
        ..f6bbfbbbbbbffff......
        ..f66bfbbbbbfbbbbf.....
        ..f666fbbbbfbbbb6f.....
        ...fff.ffffbbbbb66f....
        ...........fb66666f....
        ...........f666666f....
        ............ffffff.....
        .......................
        ........f..............
        ..........f............
        .......................
        `],
    150,
    true
    )
    animation.runImageAnimation(
    PIZZA,
    [img`
        .......................
        .......................
        .......................
        .......................
        .......f....ffff.......
        ......f...ffeaaf.......
        .........feeefff....f..
        ........feeff557f......
        .......feef555fff...f..
        ......feef555f22f......
        .....feef5555f22f......
        .....fef5ff555ff5f.....
        ....feeff22f55555f.....
        ....faf5f27f55557f.....
        ....fea55ff555557f.....
        ....fff5555555ff57f....
        .......fffff5f27f7f....
        ...........ffff277f....
        ...............ffff....
        .......................
        ........f..f...........
        .......................
        .......................
        `,img`
        .......................
        .......................
        ..........f..f.........
        .......................
        ............ffff.......
        ..........ffeaaf.......
        .........feeefff.......
        ........feeff557f......
        .......feef555fff......
        ......feef555f22f......
        .....feef5555f22f......
        .....fef5ff555ff5f...f.
        ....feeff22f55555f.....
        ....faf5f27f55557f.....
        ....fea55ff555557f...f.
        ....fff5555555ff57f....
        .......fffff5f27f7f....
        ...........ffff277f....
        ...f...........ffff....
        ......f................
        .......................
        .......................
        .......................
        `,img`
        .......................
        .......................
        .................f.....
        .......................
        ............ffff...f...
        ..........ffeaaf.......
        .........feeefff.......
        ........feeff557f......
        .......feef555fff......
        ......feef555f22f......
        .....feef5555f22f......
        .....fef5ff555ff5f.....
        ....feeff22f55555f.....
        ....faf5f27f55557f.....
        ..f.fea55ff555557f.....
        ....fff5555555ff57f....
        ..f....fffff5f27f7f....
        ...........ffff277f..f.
        ...............ffff....
        ....................f..
        .......................
        .......................
        .......................
        `,img`
        .......................
        .......................
        .......................
        .......................
        ............ffff.......
        ..........ffeaaf.......
        .........feeefff....f..
        ........feeff557f......
        .......feef555fff...f..
        ......feef555f22f......
        ...f.feef5555f22f......
        .....fef5ff555ff5f.....
        ..f.feeff22f55555f.....
        ....faf5f27f55557f.....
        ....fea55ff555557f.....
        ....fff5555555ff57f....
        .......fffff5f27f7f....
        ...........ffff277f....
        ...............ffff....
        .......................
        ...............f.......
        ..................f....
        .......................
        `,img`
        .......................
        .......................
        .......................
        .......................
        ............ffff.......
        ......f...ffeaaf.......
        .........feeefff.......
        ....f...feeff557f...f..
        .......feef555fff......
        ......feef555f22f......
        .....feef5555f22f...f..
        .....fef5ff555ff5f.....
        ....feeff22f55555f.....
        ....faf5f27f55557f...f.
        ....fea55ff555557f.....
        ....fff5555555ff57f....
        .......fffff5f27f7f....
        ...........ffff277f....
        ...............ffff....
        ..........f............
        ............f..........
        .......................
        .......................
        `],
    150,
    true
    )
}
let PIZZA: Sprite = null
let BASURA: Sprite = null
let countPizzas = 0
let PLAYER: Sprite = null
let txtPizzas: TextSprite = null
info.setScore(0)
txtPizzas = textsprite.create("Pizzas: 0", 0, 2)
txtPizzas.setPosition(40, 10)
tiles.setCurrentTilemap(tilemap`nivel1`)
PLAYER = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . f f f f f f f . . . . 
    . . . . f d 1 1 1 1 1 d f . . . 
    . . . f d 1 1 1 1 1 1 1 d f . . 
    . . . f 1 1 f 1 1 1 f 1 1 f . . 
    . . . f 1 1 f 1 1 1 f 1 1 f . . 
    . . . f 1 1 1 1 1 1 1 1 1 f . . 
    . . . f 1 1 1 1 1 1 1 1 1 f . . 
    . . . . f d 1 1 1 1 1 d f . . . 
    . . . . . f 1 1 1 1 1 f . . . . 
    . . . . . f 1 1 1 1 1 f . . . . 
    . . . . . f 1 1 1 1 1 f . . . . 
    . . . . . f 1 d f 1 1 f . . . . 
    . . . . . f d f . f d f . . . . 
    . . . . . f f . . f f f . . . . 
    `, SpriteKind.Player)
controller.moveSprite(PLAYER)
scene.cameraFollowSprite(PLAYER)
game.onUpdateInterval(4000, function () {
    Crear_Basura()
})
